#!/bin/bash

#Make "sse" directory on your home directory
mkdir sse

#create hello.c on the directory
cd sse

#create script with echo
echo "
#include <stdio.h>

int main(void)
{
	printf(\"hello, world\n\");
	return 0;
}
" > hello.c

#compile it
gcc -o hello hello.c

#run the program
./hello

#remove "sse" directory
cd ..
rm -r sse



